# Yarn config
# Building fails with global cache, use this to fix it
# https://kit.svelte.dev/docs/faq#how-do-i-use-x-with-sveltekit-how-do-i-use-with-yarn-3-yarn-3-global-cache
nodeLinker: node-modules

plugins:
  - checksum: 0a11ea4f225c5180bdd8c7f6d2cbcb53c15fb8f0ba92d3b8bcdab9c321ffb0f9095119a92672e445a226411c6576bda8bbdb16b2b806c6850e9729fe7c032d5d
    path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"
